apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiarmbandit-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiarmbandit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: multiarmbandit
    spec:
      containers:
      - name: hello-pod
        image: vibhutis/multiarmbandit
        ports:
        - containerPort: 80
