apiVersion: v1
kind: Service
metadata:
  name: multiarmbandit
spec:
# ipFamilyPolicy: PreferDualStack
# ipFamilies:
# - IPv4
# - IPv6
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 80
  selector:
    app: multiarmbandit
