apiVersion: v1
kind: Service
metadata:
  name: multiarmbandit-lb
spec:
# ipFamilyPolicy: PreferDualStack
# ipFamilies:
# - IPv4
# - IPv6
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: multiarmbandit
